import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

const translations = {
  en: {
    // Nav sections
    navMarkets: 'Markets', navPortfolio: 'Portfolio', navDefi: 'DeFi', navAccount: 'Account',
    // Nav items
    dashboard: 'Dashboard', markets: 'Markets', trade: 'Trade', history: 'History',
    wallet: 'Wallet', assets: 'Assets', staking: 'Staking', nfts: 'NFTs',
    settings: 'Settings', logout: 'Logout',
    // Topbar
    deposit: 'Deposit', tradeNow: 'Trade Now', notLoggedIn: 'Not logged in',
    // Dashboard
    totalPortfolioValue: 'Total Portfolio Value', myWatchlist: 'My Watchlist',
    recentActivity: 'Recent Activity', viewAll: 'View All', viewFullHistory: 'View Full History',
    portfolioAllocation: 'Portfolio Allocation', manage: 'MANAGE', topAssets: 'Top Assets',
    plToday: 'P&L TODAY', plAllTime: 'P&L ALL TIME', lastDays: 'Last 7 days',
    // Stats
    marketCap: 'Market Cap', volume24h: '24h Volume', athDistance: 'ATH Distance',
    btcDominance: 'BTC Dominance',
    // Market table
    asset: 'Asset', price: 'Price', change24h: '24h Change', volume: 'Volume', chart7d: '7D Chart',
    // Watchlist
    addToWatchlist: 'Add to Watchlist', noCoinsWatchlist: 'No coins in watchlist',
    addFirstCoin: 'Add Your First Coin', allCoinsAdded: 'All coins are already in your watchlist!',
    removeFromWatchlist: 'Remove from watchlist',
    // Activity
    noRecentActivity: 'No recent activity', startTrading: 'Start Trading',
    secAgo: 'sec ago', minAgo: 'min ago', hourAgo: 'hour ago', hoursAgo: 'hours ago',
    dayAgo: 'day ago', daysAgo: 'days ago',
    // Transaction types
    txDeposit: 'Deposit', txSent: 'Sent', txBought: 'Bought', txWithdraw: 'Withdraw',
    txSwapped: 'Swapped', txSold: 'Sold',
    // Status
    completed: 'Completed', pending: 'Pending', failed: 'Failed',
    // Actions
    buy: 'Buy', sell: 'Sell', send: 'Send', receive: 'Receive', swap: 'Swap',
    cancel: 'Cancel', confirm: 'Confirm', save: 'Save', close: 'Close',
    search: 'Search', filter: 'Filter', loading: 'Loading...', error: 'Error', success: 'Success',
    // Wallet
    totalBalance: 'Total Balance', availableBalance: 'Available Balance',
    // Trade
    orderBook: 'Order Book', recentTrades: 'Recent Trades', buyOrder: 'Buy', sellOrder: 'Sell',
    amount: 'Amount', total: 'Total', spread: 'spread',
    // Settings
    profile: 'Profile', security: 'Security', notifications: 'Notifications',
    appearance: 'Appearance', language: 'Language', saveChanges: 'Save Changes',
    // Markets
    searchCoins: 'Search coins — Bitcoin, BTC, ETH...', trending: 'Trending',
    gainers: 'Top Gainers', losers: 'Top Losers', all: 'All',
    // Staking
    stake: 'Stake', unstake: 'Unstake', apy: 'APY', rewards: 'Rewards',
    myStakes: 'My Stakes', availablePools: 'Available Pools',
    totalStaked: 'Total Staked', totalEarned: 'Total Earned', activeStakes: 'Active Stakes',
    stakeNow: 'Stake Now', confirmStake: 'Confirm Stake', enterAmount: 'Enter Amount to Stake',
    estimatedRewards: 'Estimated Rewards', daily: 'Daily', monthly: 'Monthly', yearly: 'Yearly',
    noActiveStakes: 'No Active Stakes', startStaking: 'Start staking your crypto to earn rewards',
    viewAvailablePools: 'View Available Pools',
    // NFTs
    explore: 'Explore', myNfts: 'My NFTs', floorPrice: 'Floor Price',
    nftMarketplace: 'NFT Marketplace', collections: 'Collections',
    buyNow: 'Buy Now', listForSale: 'List for Sale', transfer: 'Transfer',
    confirmPurchase: 'Confirm Purchase', insufficientBalance: 'Insufficient Balance',
    filters: 'Filters', allCategories: 'All Categories', allRarities: 'All Rarities',
    allBlockchains: 'All Blockchains', priceRange: 'Price Range',
    viewCollection: 'View Collection', nftsOwned: 'NFTs Owned',
    totalValue: 'Total Value', totalProfit: 'Total Profit', walletBalance: 'Wallet Balance',
    // Auth
    emailAddress: 'Email Address', password: 'Password', fullName: 'Full Name',
    signIn: 'Sign In', signUp: 'Sign Up', forgotPassword: 'Forgot Password?',
    noAccount: "Don't have an account?", hasAccount: 'Already have an account?',
    // Signup
    signUpSubtitle: 'Sign up to start trading', enterFullName: 'Enter your full name',
    enterEmail: 'Enter your email', confirmPassword: 'Confirm Password',
    creatingAccount: 'Creating account...',
    // Forgot Password
    fpStepEmail: 'Email', fpStepVerify: 'Verify', fpStepReset: 'Reset', fpStepDone: 'Done',
    fpEmailSubtitle: "Enter your email and we'll send you a reset code.",
    sendResetCode: 'Send Reset Code', backToLogin: 'Back to Login', sending: 'Sending...',
    checkYourEmail: 'Check Your Email', fpOtpSubtitle: 'We sent a 6-digit code to',
    verifyCode: 'Verify Code', verifying: 'Verifying...', resendIn: 'Resend code in',
    resendCode: 'Resend Code', changeEmail: 'Change email',
    setNewPassword: 'Set New Password', fpPasswordSubtitle: 'Choose a strong password for your account.',
    newPassword: 'New Password', enterNewPassword: 'Enter new password',
    confirmNewPassword: 'Confirm new password', passwordsMatch: 'Passwords match',
    passwordsNoMatch: 'Passwords do not match', saving: 'Saving...', resetPassword: 'Reset Password',
    passwordReset: 'Password Reset!', passwordResetSuccess: 'Your password has been updated successfully.',
    // Deposit
    depositSubtitle: 'Select the method you want to use to deposit funds to your account.',
    // Withdraw
    withdraw: 'Withdraw', withdrawSubtitle: 'Transfer funds to your bank, card, or crypto wallet',
    fiatCurrency: 'Fiat Currency', cryptocurrency: 'Cryptocurrency',
    selectWithdrawMethod: 'Select Withdrawal Method', withdrawalDetails: 'Withdrawal Details',
    withdrawFunds: 'Withdraw Funds', processing: 'Processing…', cryptoWithdrawal: 'Crypto Withdrawal',
    // Trade
    selectTimer: 'Select Timer', indicators: 'Indicators', byMarket: 'BY MARKET',
    // Buy Crypto
    buyCrypto: 'Buy Cryptocurrency', buyCryptoSubtitle: 'Purchase crypto with multiple payment methods',
    card: 'Card', wireTransfer: 'Wire Transfer', p2pTrading: 'P2P Trading', giftCard: 'Gift Card',
    selectAmount: 'Select Amount', youPay: 'You Pay', youReceive: 'You Receive', now: 'Now',
    continueWithPaypal: 'Continue with PayPal', sentWireTransfer: "I've Sent the Wire Transfer",
    redeemGiftCard: 'Redeem Gift Card',
    // Fear & Greed
    fearGreed: 'Fear & Greed Index', fear: 'FEAR', neutral: 'NEUTRAL', greed: 'GREED',
    updatedAgo: 'UPDATED 1H AGO',
  },
  es: {
    navMarkets: 'Mercados', navPortfolio: 'Portafolio', navDefi: 'DeFi', navAccount: 'Cuenta',
    dashboard: 'Panel', markets: 'Mercados', trade: 'Operar', history: 'Historial',
    wallet: 'Billetera', assets: 'Activos', staking: 'Staking', nfts: 'NFTs',
    settings: 'Configuración', logout: 'Cerrar sesión',
    deposit: 'Depositar', tradeNow: 'Operar Ahora', notLoggedIn: 'No conectado',
    totalPortfolioValue: 'Valor Total del Portafolio', myWatchlist: 'Mi Lista',
    recentActivity: 'Actividad Reciente', viewAll: 'Ver Todo', viewFullHistory: 'Ver Historial Completo',
    portfolioAllocation: 'Asignación del Portafolio', manage: 'GESTIONAR', topAssets: 'Principales Activos',
    plToday: 'G/P HOY', plAllTime: 'G/P TOTAL', lastDays: 'Últimos 7 días',
    marketCap: 'Cap. de Mercado', volume24h: 'Volumen 24h', athDistance: 'Dist. ATH',
    btcDominance: 'Dominancia BTC',
    asset: 'Activo', price: 'Precio', change24h: 'Cambio 24h', volume: 'Volumen', chart7d: 'Gráfico 7D',
    addToWatchlist: 'Agregar a Lista', noCoinsWatchlist: 'Sin monedas en la lista',
    addFirstCoin: 'Agregar Primera Moneda', allCoinsAdded: '¡Todas las monedas ya están en tu lista!',
    removeFromWatchlist: 'Eliminar de la lista',
    noRecentActivity: 'Sin actividad reciente', startTrading: 'Comenzar a Operar',
    secAgo: 'seg atrás', minAgo: 'min atrás', hourAgo: 'hora atrás', hoursAgo: 'horas atrás',
    dayAgo: 'día atrás', daysAgo: 'días atrás',
    txDeposit: 'Depósito', txSent: 'Enviado', txBought: 'Comprado', txWithdraw: 'Retiro',
    txSwapped: 'Intercambiado', txSold: 'Vendido',
    completed: 'Completado', pending: 'Pendiente', failed: 'Fallido',
    buy: 'Comprar', sell: 'Vender', send: 'Enviar', receive: 'Recibir', swap: 'Intercambiar',
    cancel: 'Cancelar', confirm: 'Confirmar', save: 'Guardar', close: 'Cerrar',
    search: 'Buscar', filter: 'Filtrar', loading: 'Cargando...', error: 'Error', success: 'Éxito',
    totalBalance: 'Saldo Total', availableBalance: 'Saldo Disponible',
    orderBook: 'Libro de Órdenes', recentTrades: 'Operaciones Recientes', buyOrder: 'Comprar', sellOrder: 'Vender',
    amount: 'Cantidad', total: 'Total', spread: 'diferencial',
    profile: 'Perfil', security: 'Seguridad', notifications: 'Notificaciones',
    appearance: 'Apariencia', language: 'Idioma', saveChanges: 'Guardar Cambios',
    searchCoins: 'Buscar monedas — Bitcoin, BTC, ETH...', trending: 'Tendencias',
    gainers: 'Mayores Ganancias', losers: 'Mayores Pérdidas', all: 'Todos',
    stake: 'Apostar', unstake: 'Retirar', apy: 'APY', rewards: 'Recompensas',
    myStakes: 'Mis Stakes', availablePools: 'Pools Disponibles',
    totalStaked: 'Total Apostado', totalEarned: 'Total Ganado', activeStakes: 'Stakes Activos',
    stakeNow: 'Apostar Ahora', confirmStake: 'Confirmar Stake', enterAmount: 'Ingresa Monto',
    estimatedRewards: 'Recompensas Estimadas', daily: 'Diario', monthly: 'Mensual', yearly: 'Anual',
    noActiveStakes: 'Sin Stakes Activos', startStaking: 'Comienza a apostar para ganar recompensas',
    viewAvailablePools: 'Ver Pools Disponibles',
    explore: 'Explorar', myNfts: 'Mis NFTs', floorPrice: 'Precio Mínimo',
    nftMarketplace: 'Mercado NFT', collections: 'Colecciones',
    buyNow: 'Comprar Ahora', listForSale: 'Listar para Venta', transfer: 'Transferir',
    confirmPurchase: 'Confirmar Compra', insufficientBalance: 'Saldo Insuficiente',
    filters: 'Filtros', allCategories: 'Todas las Categorías', allRarities: 'Todas las Rarezas',
    allBlockchains: 'Todas las Blockchains', priceRange: 'Rango de Precio',
    viewCollection: 'Ver Colección', nftsOwned: 'NFTs Poseídos',
    totalValue: 'Valor Total', totalProfit: 'Ganancia Total', walletBalance: 'Saldo de Billetera',
    emailAddress: 'Correo Electrónico', password: 'Contraseña', fullName: 'Nombre Completo',
    signIn: 'Iniciar Sesión', signUp: 'Registrarse', forgotPassword: '¿Olvidaste tu contraseña?',
    noAccount: '¿No tienes cuenta?', hasAccount: '¿Ya tienes cuenta?',
    signUpSubtitle: 'Regístrate para comenzar a operar', enterFullName: 'Ingresa tu nombre completo',
    enterEmail: 'Ingresa tu correo', confirmPassword: 'Confirmar Contraseña',
    creatingAccount: 'Creando cuenta...',
    fpStepEmail: 'Correo', fpStepVerify: 'Verificar', fpStepReset: 'Restablecer', fpStepDone: 'Listo',
    fpEmailSubtitle: 'Ingresa tu correo y te enviaremos un código.',
    sendResetCode: 'Enviar Código', backToLogin: 'Volver al Login', sending: 'Enviando...',
    checkYourEmail: 'Revisa tu Correo', fpOtpSubtitle: 'Enviamos un código de 6 dígitos a',
    verifyCode: 'Verificar Código', verifying: 'Verificando...', resendIn: 'Reenviar en',
    resendCode: 'Reenviar Código', changeEmail: 'Cambiar correo',
    setNewPassword: 'Nueva Contraseña', fpPasswordSubtitle: 'Elige una contraseña segura.',
    newPassword: 'Nueva Contraseña', enterNewPassword: 'Ingresa nueva contraseña',
    confirmNewPassword: 'Confirma nueva contraseña', passwordsMatch: 'Las contraseñas coinciden',
    passwordsNoMatch: 'Las contraseñas no coinciden', saving: 'Guardando...', resetPassword: 'Restablecer Contraseña',
    passwordReset: '¡Contraseña Restablecida!', passwordResetSuccess: 'Tu contraseña fue actualizada.',
    depositSubtitle: 'Selecciona el método para depositar fondos.',
    withdraw: 'Retirar', withdrawSubtitle: 'Transfiere fondos a tu banco, tarjeta o billetera',
    fiatCurrency: 'Moneda Fiat', cryptocurrency: 'Criptomoneda',
    selectWithdrawMethod: 'Seleccionar Método de Retiro', withdrawalDetails: 'Detalles del Retiro',
    withdrawFunds: 'Retirar Fondos', processing: 'Procesando…', cryptoWithdrawal: 'Retiro Cripto',
    selectTimer: 'Seleccionar Tiempo', indicators: 'Indicadores', byMarket: 'POR MERCADO',
    buyCrypto: 'Comprar Criptomoneda', buyCryptoSubtitle: 'Compra cripto con múltiples métodos de pago',
    card: 'Tarjeta', wireTransfer: 'Transferencia Bancaria', p2pTrading: 'Trading P2P', giftCard: 'Tarjeta de Regalo',
    selectAmount: 'Seleccionar Monto', youPay: 'Pagas', youReceive: 'Recibes', now: 'Ahora',
    continueWithPaypal: 'Continuar con PayPal', sentWireTransfer: 'He Enviado la Transferencia',
    redeemGiftCard: 'Canjear Tarjeta de Regalo',
    fearGreed: 'Índice Miedo y Codicia', fear: 'MIEDO', neutral: 'NEUTRAL', greed: 'CODICIA',
    updatedAgo: 'ACTUALIZADO HACE 1H',
  },
  fr: {
    navMarkets: 'Marchés', navPortfolio: 'Portefeuille', navDefi: 'DeFi', navAccount: 'Compte',
    dashboard: 'Tableau de bord', markets: 'Marchés', trade: 'Trader', history: 'Historique',
    wallet: 'Portefeuille', assets: 'Actifs', staking: 'Staking', nfts: 'NFTs',
    settings: 'Paramètres', logout: 'Déconnexion',
    deposit: 'Dépôt', tradeNow: 'Trader Maintenant', notLoggedIn: 'Non connecté',
    totalPortfolioValue: 'Valeur Totale du Portefeuille', myWatchlist: 'Ma Liste',
    recentActivity: 'Activité Récente', viewAll: 'Voir Tout', viewFullHistory: 'Voir Historique Complet',
    portfolioAllocation: 'Allocation du Portefeuille', manage: 'GÉRER', topAssets: 'Principaux Actifs',
    plToday: "G/P AUJOURD'HUI", plAllTime: 'G/P TOTAL', lastDays: '7 derniers jours',
    marketCap: 'Cap. Marché', volume24h: 'Volume 24h', athDistance: 'Dist. ATH',
    btcDominance: 'Dominance BTC',
    asset: 'Actif', price: 'Prix', change24h: 'Variation 24h', volume: 'Volume', chart7d: 'Graphique 7J',
    addToWatchlist: 'Ajouter à la Liste', noCoinsWatchlist: 'Aucune monnaie dans la liste',
    addFirstCoin: 'Ajouter Votre Première Monnaie', allCoinsAdded: 'Toutes les monnaies sont déjà dans votre liste!',
    removeFromWatchlist: 'Retirer de la liste',
    noRecentActivity: 'Aucune activité récente', startTrading: 'Commencer à Trader',
    secAgo: 'sec', minAgo: 'min', hourAgo: 'heure', hoursAgo: 'heures',
    dayAgo: 'jour', daysAgo: 'jours',
    txDeposit: 'Dépôt', txSent: 'Envoyé', txBought: 'Acheté', txWithdraw: 'Retrait',
    txSwapped: 'Échangé', txSold: 'Vendu',
    completed: 'Complété', pending: 'En attente', failed: 'Échoué',
    buy: 'Acheter', sell: 'Vendre', send: 'Envoyer', receive: 'Recevoir', swap: 'Échanger',
    cancel: 'Annuler', confirm: 'Confirmer', save: 'Enregistrer', close: 'Fermer',
    search: 'Rechercher', filter: 'Filtrer', loading: 'Chargement...', error: 'Erreur', success: 'Succès',
    totalBalance: 'Solde Total', availableBalance: 'Solde Disponible',
    orderBook: 'Carnet d\'Ordres', recentTrades: 'Trades Récents', buyOrder: 'Acheter', sellOrder: 'Vendre',
    amount: 'Montant', total: 'Total', spread: 'écart',
    profile: 'Profil', security: 'Sécurité', notifications: 'Notifications',
    appearance: 'Apparence', language: 'Langue', saveChanges: 'Enregistrer',
    searchCoins: 'Rechercher — Bitcoin, BTC, ETH...', trending: 'Tendances',
    gainers: 'Meilleures Hausses', losers: 'Meilleures Baisses', all: 'Tous',
    stake: 'Staker', unstake: 'Retirer', apy: 'APY', rewards: 'Récompenses',
    myStakes: 'Mes Stakes', availablePools: 'Pools Disponibles',
    totalStaked: 'Total Staké', totalEarned: 'Total Gagné', activeStakes: 'Stakes Actifs',
    stakeNow: 'Staker Maintenant', confirmStake: 'Confirmer le Stake', enterAmount: 'Entrer le Montant',
    estimatedRewards: 'Récompenses Estimées', daily: 'Quotidien', monthly: 'Mensuel', yearly: 'Annuel',
    noActiveStakes: 'Aucun Stake Actif', startStaking: 'Commencez à staker pour gagner des récompenses',
    viewAvailablePools: 'Voir les Pools Disponibles',
    explore: 'Explorer', myNfts: 'Mes NFTs', floorPrice: 'Prix Plancher',
    nftMarketplace: 'Marché NFT', collections: 'Collections',
    buyNow: 'Acheter Maintenant', listForSale: 'Mettre en Vente', transfer: 'Transférer',
    confirmPurchase: 'Confirmer l\'Achat', insufficientBalance: 'Solde Insuffisant',
    filters: 'Filtres', allCategories: 'Toutes les Catégories', allRarities: 'Toutes les Raretés',
    allBlockchains: 'Toutes les Blockchains', priceRange: 'Fourchette de Prix',
    viewCollection: 'Voir la Collection', nftsOwned: 'NFTs Possédés',
    totalValue: 'Valeur Totale', totalProfit: 'Profit Total', walletBalance: 'Solde du Portefeuille',
    emailAddress: 'Adresse Email', password: 'Mot de passe', fullName: 'Nom Complet',
    signIn: 'Se Connecter', signUp: "S'inscrire", forgotPassword: 'Mot de passe oublié?',
    noAccount: 'Pas de compte?', hasAccount: 'Déjà un compte?',
    signUpSubtitle: "Inscrivez-vous pour commencer", enterFullName: 'Entrez votre nom',
    enterEmail: 'Entrez votre email', confirmPassword: 'Confirmer le mot de passe',
    creatingAccount: 'Création du compte...',
    fpStepEmail: 'Email', fpStepVerify: 'Vérifier', fpStepReset: 'Réinitialiser', fpStepDone: 'Terminé',
    fpEmailSubtitle: 'Entrez votre email et nous vous enverrons un code.',
    sendResetCode: 'Envoyer le Code', backToLogin: 'Retour à la Connexion', sending: 'Envoi...',
    checkYourEmail: 'Vérifiez votre Email', fpOtpSubtitle: 'Nous avons envoyé un code à 6 chiffres à',
    verifyCode: 'Vérifier le Code', verifying: 'Vérification...', resendIn: 'Renvoyer dans',
    resendCode: 'Renvoyer le Code', changeEmail: "Changer l'email",
    setNewPassword: 'Nouveau Mot de Passe', fpPasswordSubtitle: 'Choisissez un mot de passe fort.',
    newPassword: 'Nouveau Mot de Passe', enterNewPassword: 'Entrez le nouveau mot de passe',
    confirmNewPassword: 'Confirmez le nouveau mot de passe', passwordsMatch: 'Les mots de passe correspondent',
    passwordsNoMatch: 'Les mots de passe ne correspondent pas', saving: 'Enregistrement...', resetPassword: 'Réinitialiser',
    passwordReset: 'Mot de Passe Réinitialisé!', passwordResetSuccess: 'Votre mot de passe a été mis à jour.',
    depositSubtitle: 'Sélectionnez la méthode pour déposer des fonds.',
    withdraw: 'Retrait', withdrawSubtitle: 'Transférez des fonds vers votre banque, carte ou portefeuille',
    fiatCurrency: 'Monnaie Fiduciaire', cryptocurrency: 'Cryptomonnaie',
    selectWithdrawMethod: 'Sélectionner la Méthode', withdrawalDetails: 'Détails du Retrait',
    withdrawFunds: 'Retirer les Fonds', processing: 'Traitement…', cryptoWithdrawal: 'Retrait Crypto',
    selectTimer: 'Sélectionner le Temps', indicators: 'Indicateurs', byMarket: 'AU MARCHÉ',
    buyCrypto: 'Acheter des Cryptos', buyCryptoSubtitle: 'Achetez des cryptos avec plusieurs méthodes',
    card: 'Carte', wireTransfer: 'Virement Bancaire', p2pTrading: 'Trading P2P', giftCard: 'Carte Cadeau',
    selectAmount: 'Sélectionner le Montant', youPay: 'Vous Payez', youReceive: 'Vous Recevez', now: 'Maintenant',
    continueWithPaypal: 'Continuer avec PayPal', sentWireTransfer: "J'ai Envoyé le Virement",
    redeemGiftCard: 'Échanger la Carte Cadeau',
    fearGreed: 'Indice Peur et Avidité', fear: 'PEUR', neutral: 'NEUTRE', greed: 'AVIDITÉ',
    updatedAgo: 'MIS À JOUR IL Y A 1H',
  },
  de: {
    navMarkets: 'Märkte', navPortfolio: 'Portfolio', navDefi: 'DeFi', navAccount: 'Konto',
    dashboard: 'Dashboard', markets: 'Märkte', trade: 'Handeln', history: 'Verlauf',
    wallet: 'Wallet', assets: 'Vermögen', staking: 'Staking', nfts: 'NFTs',
    settings: 'Einstellungen', logout: 'Abmelden',
    deposit: 'Einzahlen', tradeNow: 'Jetzt Handeln', notLoggedIn: 'Nicht angemeldet',
    totalPortfolioValue: 'Gesamter Portfoliowert', myWatchlist: 'Meine Watchlist',
    recentActivity: 'Letzte Aktivität', viewAll: 'Alle Anzeigen', viewFullHistory: 'Vollständigen Verlauf',
    portfolioAllocation: 'Portfolio-Aufteilung', manage: 'VERWALTEN', topAssets: 'Top Vermögen',
    plToday: 'G/V HEUTE', plAllTime: 'G/V GESAMT', lastDays: 'Letzte 7 Tage',
    marketCap: 'Marktkapitalisierung', volume24h: '24h Volumen', athDistance: 'ATH Abstand',
    btcDominance: 'BTC Dominanz',
    asset: 'Vermögen', price: 'Preis', change24h: '24h Änderung', volume: 'Volumen', chart7d: '7T Chart',
    addToWatchlist: 'Zur Watchlist', noCoinsWatchlist: 'Keine Coins in der Watchlist',
    addFirstCoin: 'Ersten Coin Hinzufügen', allCoinsAdded: 'Alle Coins sind bereits in Ihrer Watchlist!',
    removeFromWatchlist: 'Von Watchlist entfernen',
    noRecentActivity: 'Keine letzte Aktivität', startTrading: 'Handel Starten',
    secAgo: 'Sek.', minAgo: 'Min.', hourAgo: 'Std.', hoursAgo: 'Std.',
    dayAgo: 'Tag', daysAgo: 'Tage',
    txDeposit: 'Einzahlung', txSent: 'Gesendet', txBought: 'Gekauft', txWithdraw: 'Auszahlung',
    txSwapped: 'Getauscht', txSold: 'Verkauft',
    completed: 'Abgeschlossen', pending: 'Ausstehend', failed: 'Fehlgeschlagen',
    buy: 'Kaufen', sell: 'Verkaufen', send: 'Senden', receive: 'Empfangen', swap: 'Tauschen',
    cancel: 'Abbrechen', confirm: 'Bestätigen', save: 'Speichern', close: 'Schließen',
    search: 'Suchen', filter: 'Filtern', loading: 'Laden...', error: 'Fehler', success: 'Erfolg',
    totalBalance: 'Gesamtsaldo', availableBalance: 'Verfügbarer Saldo',
    orderBook: 'Orderbuch', recentTrades: 'Letzte Trades', buyOrder: 'Kaufen', sellOrder: 'Verkaufen',
    amount: 'Betrag', total: 'Gesamt', spread: 'Spread',
    profile: 'Profil', security: 'Sicherheit', notifications: 'Benachrichtigungen',
    appearance: 'Erscheinungsbild', language: 'Sprache', saveChanges: 'Änderungen Speichern',
    searchCoins: 'Suchen — Bitcoin, BTC, ETH...', trending: 'Trending',
    gainers: 'Top Gewinner', losers: 'Top Verlierer', all: 'Alle',
    stake: 'Staken', unstake: 'Entstaken', apy: 'APY', rewards: 'Belohnungen',
    myStakes: 'Meine Stakes', availablePools: 'Verfügbare Pools',
    totalStaked: 'Gesamt Gestakt', totalEarned: 'Gesamt Verdient', activeStakes: 'Aktive Stakes',
    stakeNow: 'Jetzt Staken', confirmStake: 'Stake Bestätigen', enterAmount: 'Betrag Eingeben',
    estimatedRewards: 'Geschätzte Belohnungen', daily: 'Täglich', monthly: 'Monatlich', yearly: 'Jährlich',
    noActiveStakes: 'Keine Aktiven Stakes', startStaking: 'Staken Sie Ihre Krypto für Belohnungen',
    viewAvailablePools: 'Verfügbare Pools Anzeigen',
    explore: 'Erkunden', myNfts: 'Meine NFTs', floorPrice: 'Mindestpreis',
    nftMarketplace: 'NFT-Marktplatz', collections: 'Sammlungen',
    buyNow: 'Jetzt Kaufen', listForSale: 'Zum Verkauf Anbieten', transfer: 'Übertragen',
    confirmPurchase: 'Kauf Bestätigen', insufficientBalance: 'Unzureichendes Guthaben',
    filters: 'Filter', allCategories: 'Alle Kategorien', allRarities: 'Alle Seltenheiten',
    allBlockchains: 'Alle Blockchains', priceRange: 'Preisbereich',
    viewCollection: 'Sammlung Anzeigen', nftsOwned: 'Besessene NFTs',
    totalValue: 'Gesamtwert', totalProfit: 'Gesamtgewinn', walletBalance: 'Wallet-Guthaben',
    emailAddress: 'E-Mail-Adresse', password: 'Passwort', fullName: 'Vollständiger Name',
    signIn: 'Anmelden', signUp: 'Registrieren', forgotPassword: 'Passwort vergessen?',
    noAccount: 'Kein Konto?', hasAccount: 'Bereits ein Konto?',
    signUpSubtitle: 'Registrieren Sie sich zum Handeln', enterFullName: 'Vollständigen Namen eingeben',
    enterEmail: 'E-Mail eingeben', confirmPassword: 'Passwort bestätigen',
    creatingAccount: 'Konto wird erstellt...',
    fpStepEmail: 'E-Mail', fpStepVerify: 'Verifizieren', fpStepReset: 'Zurücksetzen', fpStepDone: 'Fertig',
    fpEmailSubtitle: 'Geben Sie Ihre E-Mail ein und wir senden Ihnen einen Code.',
    sendResetCode: 'Code Senden', backToLogin: 'Zurück zur Anmeldung', sending: 'Senden...',
    checkYourEmail: 'E-Mail Prüfen', fpOtpSubtitle: 'Wir haben einen 6-stelligen Code gesendet an',
    verifyCode: 'Code Verifizieren', verifying: 'Verifizierung...', resendIn: 'Erneut senden in',
    resendCode: 'Code Erneut Senden', changeEmail: 'E-Mail ändern',
    setNewPassword: 'Neues Passwort', fpPasswordSubtitle: 'Wählen Sie ein sicheres Passwort.',
    newPassword: 'Neues Passwort', enterNewPassword: 'Neues Passwort eingeben',
    confirmNewPassword: 'Neues Passwort bestätigen', passwordsMatch: 'Passwörter stimmen überein',
    passwordsNoMatch: 'Passwörter stimmen nicht überein', saving: 'Speichern...', resetPassword: 'Passwort Zurücksetzen',
    passwordReset: 'Passwort Zurückgesetzt!', passwordResetSuccess: 'Ihr Passwort wurde aktualisiert.',
    depositSubtitle: 'Wählen Sie die Methode zum Einzahlen.',
    withdraw: 'Auszahlen', withdrawSubtitle: 'Überweisen Sie Gelder an Ihre Bank, Karte oder Wallet',
    fiatCurrency: 'Fiat-Währung', cryptocurrency: 'Kryptowährung',
    selectWithdrawMethod: 'Auszahlungsmethode Wählen', withdrawalDetails: 'Auszahlungsdetails',
    withdrawFunds: 'Gelder Auszahlen', processing: 'Verarbeitung…', cryptoWithdrawal: 'Krypto-Auszahlung',
    selectTimer: 'Zeit Auswählen', indicators: 'Indikatoren', byMarket: 'MARKTPREIS',
    buyCrypto: 'Krypto Kaufen', buyCryptoSubtitle: 'Kaufen Sie Krypto mit mehreren Zahlungsmethoden',
    card: 'Karte', wireTransfer: 'Überweisung', p2pTrading: 'P2P-Handel', giftCard: 'Geschenkkarte',
    selectAmount: 'Betrag Auswählen', youPay: 'Sie Zahlen', youReceive: 'Sie Erhalten', now: 'Jetzt',
    continueWithPaypal: 'Mit PayPal Fortfahren', sentWireTransfer: 'Ich Habe die Überweisung Gesendet',
    redeemGiftCard: 'Geschenkkarte Einlösen',
    fearGreed: 'Angst & Gier Index', fear: 'ANGST', neutral: 'NEUTRAL', greed: 'GIER',
    updatedAgo: 'VOR 1 STD. AKTUALISIERT',
  },
  ar: {
    navMarkets: 'الأسواق', navPortfolio: 'المحفظة', navDefi: 'ديفاي', navAccount: 'الحساب',
    dashboard: 'لوحة التحكم', markets: 'الأسواق', trade: 'تداول', history: 'السجل',
    wallet: 'المحفظة', assets: 'الأصول', staking: 'التخزين', nfts: 'NFTs',
    settings: 'الإعدادات', logout: 'تسجيل الخروج',
    deposit: 'إيداع', tradeNow: 'تداول الآن', notLoggedIn: 'غير مسجل',
    totalPortfolioValue: 'إجمالي قيمة المحفظة', myWatchlist: 'قائمة المتابعة',
    recentActivity: 'النشاط الأخير', viewAll: 'عرض الكل', viewFullHistory: 'عرض السجل الكامل',
    portfolioAllocation: 'توزيع المحفظة', manage: 'إدارة', topAssets: 'أفضل الأصول',
    plToday: 'الربح/الخسارة اليوم', plAllTime: 'الربح/الخسارة الكلي', lastDays: 'آخر 7 أيام',
    marketCap: 'القيمة السوقية', volume24h: 'حجم 24 ساعة', athDistance: 'المسافة من ATH',
    btcDominance: 'هيمنة BTC',
    asset: 'الأصل', price: 'السعر', change24h: 'التغيير 24س', volume: 'الحجم', chart7d: 'مخطط 7 أيام',
    addToWatchlist: 'أضف للقائمة', noCoinsWatchlist: 'لا توجد عملات في القائمة',
    addFirstCoin: 'أضف أول عملة', allCoinsAdded: 'جميع العملات موجودة في قائمتك!',
    removeFromWatchlist: 'إزالة من القائمة',
    noRecentActivity: 'لا يوجد نشاط حديث', startTrading: 'ابدأ التداول',
    secAgo: 'ث', minAgo: 'د', hourAgo: 'س', hoursAgo: 'س',
    dayAgo: 'يوم', daysAgo: 'أيام',
    txDeposit: 'إيداع', txSent: 'مُرسل', txBought: 'مشترى', txWithdraw: 'سحب',
    txSwapped: 'مُبادل', txSold: 'مباع',
    completed: 'مكتمل', pending: 'معلق', failed: 'فشل',
    buy: 'شراء', sell: 'بيع', send: 'إرسال', receive: 'استقبال', swap: 'مبادلة',
    cancel: 'إلغاء', confirm: 'تأكيد', save: 'حفظ', close: 'إغلاق',
    search: 'بحث', filter: 'تصفية', loading: 'جار التحميل...', error: 'خطأ', success: 'نجاح',
    totalBalance: 'الرصيد الكلي', availableBalance: 'الرصيد المتاح',
    orderBook: 'دفتر الأوامر', recentTrades: 'الصفقات الأخيرة', buyOrder: 'شراء', sellOrder: 'بيع',
    amount: 'الكمية', total: 'الإجمالي', spread: 'الفارق',
    profile: 'الملف الشخصي', security: 'الأمان', notifications: 'الإشعارات',
    appearance: 'المظهر', language: 'اللغة', saveChanges: 'حفظ التغييرات',
    searchCoins: 'ابحث — بيتكوين، BTC، ETH...', trending: 'الرائج',
    gainers: 'أعلى الرابحين', losers: 'أعلى الخاسرين', all: 'الكل',
    stake: 'تخزين', unstake: 'إلغاء التخزين', apy: 'APY', rewards: 'المكافآت',
    myStakes: 'تخزيناتي', availablePools: 'المجمعات المتاحة',
    totalStaked: 'إجمالي المخزن', totalEarned: 'إجمالي المكتسب', activeStakes: 'التخزينات النشطة',
    stakeNow: 'خزّن الآن', confirmStake: 'تأكيد التخزين', enterAmount: 'أدخل المبلغ',
    estimatedRewards: 'المكافآت المتوقعة', daily: 'يومي', monthly: 'شهري', yearly: 'سنوي',
    noActiveStakes: 'لا توجد تخزينات نشطة', startStaking: 'ابدأ التخزين لكسب المكافآت',
    viewAvailablePools: 'عرض المجمعات المتاحة',
    explore: 'استكشاف', myNfts: 'NFTs الخاصة بي', floorPrice: 'السعر الأدنى',
    nftMarketplace: 'سوق NFT', collections: 'المجموعات',
    buyNow: 'اشتر الآن', listForSale: 'أدرج للبيع', transfer: 'تحويل',
    confirmPurchase: 'تأكيد الشراء', insufficientBalance: 'رصيد غير كافٍ',
    filters: 'فلاتر', allCategories: 'جميع الفئات', allRarities: 'جميع الندرات',
    allBlockchains: 'جميع البلوكتشين', priceRange: 'نطاق السعر',
    viewCollection: 'عرض المجموعة', nftsOwned: 'NFTs المملوكة',
    totalValue: 'القيمة الإجمالية', totalProfit: 'الربح الإجمالي', walletBalance: 'رصيد المحفظة',
    emailAddress: 'البريد الإلكتروني', password: 'كلمة المرور', fullName: 'الاسم الكامل',
    signIn: 'تسجيل الدخول', signUp: 'إنشاء حساب', forgotPassword: 'نسيت كلمة المرور؟',
    noAccount: 'ليس لديك حساب؟', hasAccount: 'لديك حساب بالفعل؟',
    signUpSubtitle: 'سجل للبدء في التداول', enterFullName: 'أدخل اسمك الكامل',
    enterEmail: 'أدخل بريدك الإلكتروني', confirmPassword: 'تأكيد كلمة المرور',
    creatingAccount: 'جار إنشاء الحساب...',
    fpStepEmail: 'البريد', fpStepVerify: 'التحقق', fpStepReset: 'إعادة التعيين', fpStepDone: 'تم',
    fpEmailSubtitle: 'أدخل بريدك الإلكتروني وسنرسل لك رمزاً.',
    sendResetCode: 'إرسال رمز الاستعادة', backToLogin: 'العودة لتسجيل الدخول', sending: 'جار الإرسال...',
    checkYourEmail: 'تحقق من بريدك', fpOtpSubtitle: 'أرسلنا رمزاً مكوناً من 6 أرقام إلى',
    verifyCode: 'التحقق من الرمز', verifying: 'جار التحقق...', resendIn: 'إعادة الإرسال خلال',
    resendCode: 'إعادة إرسال الرمز', changeEmail: 'تغيير البريد الإلكتروني',
    setNewPassword: 'تعيين كلمة مرور جديدة', fpPasswordSubtitle: 'اختر كلمة مرور قوية.',
    newPassword: 'كلمة المرور الجديدة', enterNewPassword: 'أدخل كلمة المرور الجديدة',
    confirmNewPassword: 'تأكيد كلمة المرور الجديدة', passwordsMatch: 'كلمات المرور متطابقة',
    passwordsNoMatch: 'كلمات المرور غير متطابقة', saving: 'جار الحفظ...', resetPassword: 'إعادة تعيين كلمة المرور',
    passwordReset: 'تم إعادة تعيين كلمة المرور!', passwordResetSuccess: 'تم تحديث كلمة المرور بنجاح.',
    depositSubtitle: 'اختر الطريقة التي تريد استخدامها لإيداع الأموال.',
    withdraw: 'سحب', withdrawSubtitle: 'تحويل الأموال إلى بنكك أو بطاقتك أو محفظتك',
    fiatCurrency: 'العملة الورقية', cryptocurrency: 'العملة المشفرة',
    selectWithdrawMethod: 'اختر طريقة السحب', withdrawalDetails: 'تفاصيل السحب',
    withdrawFunds: 'سحب الأموال', processing: 'جار المعالجة…', cryptoWithdrawal: 'سحب العملات المشفرة',
    selectTimer: 'اختر الوقت', indicators: 'المؤشرات', byMarket: 'بسعر السوق',
    buyCrypto: 'شراء العملات المشفرة', buyCryptoSubtitle: 'اشتر العملات المشفرة بطرق دفع متعددة',
    card: 'بطاقة', wireTransfer: 'تحويل بنكي', p2pTrading: 'تداول P2P', giftCard: 'بطاقة هدية',
    selectAmount: 'اختر المبلغ', youPay: 'تدفع', youReceive: 'تستلم', now: 'الآن',
    continueWithPaypal: 'المتابعة مع PayPal', sentWireTransfer: 'لقد أرسلت التحويل البنكي',
    redeemGiftCard: 'استبدال بطاقة الهدية',
    fearGreed: 'مؤشر الخوف والجشع', fear: 'خوف', neutral: 'محايد', greed: 'جشع',
    updatedAgo: 'تم التحديث منذ ساعة',
  },
};

export const LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
];

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'en');

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.setAttribute('lang', language);
    document.documentElement.setAttribute('dir', language === 'ar' ? 'rtl' : 'ltr');
  }, [language]);

  const t = (key) => translations[language]?.[key] || translations.en[key] || key;

  const changeLanguage = (lang) => {
    if (translations[lang]) setLanguage(lang);
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
